### ISSUE TITLE
Allow user to select parameters and variables from the model representation

### ISSUE THREAD

**Issue by RosaRomeroGomez** [uncharted-aske/HMI#228]
- Users might want to select certain parameters to tweak and certain variables to get predictions for. 
- This can be done in two ways: 1) from the models representation panel (leftmost panel) and 2) from the var or params panels themselves.

NOTE: We can assume that by default, we display all existing params and variables.

Design sketches for variables panel:
![image](https://user-images.githubusercontent.com/10552785/122432572-71081880-cf63-11eb-8699-6208fc7b7440.png)
Design sketches for parameters panel:
![image](https://user-images.githubusercontent.com/10552785/122432655-82e9bb80-cf63-11eb-9caa-c4984219a655.png)

**Comment by mj3cheun** [comment]
Temporary selector put in place until the model representation panel is complete

**Comment by RosaRomeroGomez** [comment]
This task is duplicated. Going to close it.
