### ISSUE TITLE
Update counters for model visualization to count model parameters and variables

### ISSUE THREAD

**Issue by RosaRomeroGomez** [uncharted-aske/HMI#246]
![image](https://user-images.githubusercontent.com/10552785/124636088-2557d900-de56-11eb-92b7-1ee140ed1b5b.png)

**Comment by YohannParis** [comment]
Already the case

![Screen Shot 2021-07-14 at 16 06 21](https://user-images.githubusercontent.com/636801/125686373-33da6b5a-6fad-4e65-86b3-bf872864f252.png)
