### ISSUE TITLE
Explore how to show code snippet given metadata in GroMEts

### ISSUE THREAD

**Issue by RosaRomeroGomez** [uncharted-aske/HMI#247]

**Comment by YohannParis** [comment]
Unfortunaltely Donu API doe not provide much other than the GroMET itself via their [`get-model-source`](https://galoisinc.github.io/ASKE-E/donu.html#get-model-source---get-source-code-for-a-model) endpoint.

Maybe @adamocarolli can weight in if I'm wrong. But based on how @mj3cheun implemented the Donu GroMET integration, this endpoint does not provide the _Source Code_ as promised.

**Comment by RosaRomeroGomez** [comment]
We can close this for now, it seems we will have enough metadata to display.
