### ISSUE TITLE
Provide more feedback to the user on saved run in simulate

### ISSUE THREAD

**Issue by mj3cheun** [uncharted-aske/HMI#292]
Currently there is little feedback provided when a new run is saved using the "bookmark button" in the simulate page and there is none when the button is pressed using touch click.

One way to provide feedback include changing the icon to a checkmark on click

<img width="290" alt="Screen Shot 2021-07-26 at 12 46 03 PM" src="https://user-images.githubusercontent.com/14062458/127027208-960ee541-d3ac-41af-ab06-85de05f3163b.png">

**Comment by RosaRomeroGomez** [comment]
I think we actually would rather the other option using an outline. However, instead of using a blue outline we could use the yellow selection color.
![image](https://user-images.githubusercontent.com/10552785/127028893-5dcfcc9a-d147-42a5-8014-1c7a56b11f62.png)
