### ISSUE TITLE
Expand on help messages in the simulate view

### ISSUE THREAD

**Issue by mj3cheun** [uncharted-aske/HMI#294]
Help messages in the parameters and variables panel can be expanded since it doesn’t cover all available options: 

Could change text to: 
For parameters panel: “Use the model visualization on the left or the ➕ and 🚫 buttons above to add/remove parameters.”
For variables panel: “Use the model visualization on the left or the ➕ and 🚫 buttons above to add/remove variables.”

**Comment by RosaRomeroGomez** [comment]
This has been addressed.
