### ISSUE TITLE
Fix broken subtitles for knowledge cards

### ISSUE THREAD

**Issue by mj3cheun** [uncharted-aske/HMI#310]
Currently the subtitle being generated in the docsCards view is broken. Fix the generated subtitle and use the following format:
```
[JOURNAL] [YEAR] - [AUTHOR LIST]
```

where the journal is formatted as following:
- If journal doesn't exist, then use `Unknown Journal`
- Otherwise use full journal (e.g. Elsevier)

where the year is formatted as following:
- If year doesn't exist, then use `Unknown Year`
- Otherwise use full year (e.g. 2003)

where the author list is formatted as the following:

- If authors list does not exist, then use `Unknown Author`
- If authors list has less than or equal to 3 items then format with first names and middle names abbreviated, last names full, use `and` in front of last item (e.g. J.D. Smith, and K. Adams)
- If authors list has greater than 3 items then truncate with `et al.` (e.g. J.D. Smith, K. Adams, B. Crawford, et al.)

**Comment by RosaRomeroGomez** [comment]
Just keep in mind that our priority for the demo is the Models space.

**Comment by RosaRomeroGomez** [comment]
I also noticed that by selecting a card that includes a doc artifact associated with an aske-id, our side panel seems broken. 
![image](https://user-images.githubusercontent.com/10552785/128980977-674219a6-e4e2-4734-a648-d11577d5ef28.png)

**Comment by YohannParis** [comment]
> I also noticed that by selecting a card that includes a doc artifact associated with an aske-id, our side panel seems broken. As a big hack, we should include a link back to the CHIME models once it is served by donu.
> ![image](https://user-images.githubusercontent.com/10552785/128980977-674219a6-e4e2-4734-a648-d11577d5ef28.png)

How do you know the CHIME model will be relevant for any ASKE-ID artifacts?
