### ISSUE TITLE
No default values for parameters causes an error for the parameters panel

### ISSUE THREAD

**Issue by RosaRomeroGomez** [uncharted-aske/HMI#340]
Steps to reproduce:

- Select `SimpleSIR_metadata` model.
- Open the simulation view.
- Add parameters to the parameters panel

![image](https://user-images.githubusercontent.com/10552785/128343211-95e7ceb1-08fe-4712-a563-f9013635df61.png)

**Comment by YohannParis** [comment]
This is not the case anymore.
