### ISSUE TITLE
Box selection when consecutive makes multiple boxes look selected

### ISSUE THREAD

**Issue by RosaRomeroGomez** [uncharted-aske/HMI#377]
![image](https://user-images.githubusercontent.com/10552785/129752677-1f41773e-1ff6-4a2f-b658-d50a1fc7d068.png)

**Comment by mj3cheun** [comment]
Might be a good opportunity to switch over to the new selection system, which i can confirm is not affected by this bug. However doing this could take longer than simply finding and fixing the bug in the existing system...
