### ISSUE TITLE
Include parameter plot under the Parameters tab in the Model drill-down panel

### ISSUE THREAD

**Issue by RosaRomeroGomez** [uncharted-aske/HMI#382]
- Back in February, we used some xdd extracted data to populate the Parameters tab in the Model drill-down panel to show some values extracted from documents.
- The extracted data comes from this table: http://teststrata.geology.wisc.edu/xdd/extract.php?doc_set=xdd-covid-19 (we only used two columns (variable and local, then I used date for the tooltip)
- This is how it looked like back in February:
![image](https://user-images.githubusercontent.com/10552785/129831965-8079a629-a1b8-4fa8-8f61-d6f21e92af9d.png)

This is a rough sketch of the idea I think we could quickly implement this time. We could enable a dropdown menu under the Parameters tab that allows the user to explore existing data  in that table. We can show some variable by default (e.g. R0) but allow the user to select others, which updates the scatterplot at the bottom.
![image](https://user-images.githubusercontent.com/10552785/129833391-a09c335e-f055-4354-a5e7-a031b4709964.png)

**Comment by YohannParis** [comment]
- Inside the drilldown parameters tabs for all nodes of all models. (static tab)
- The data will not change, I can clean the data and integrate it as a JSON.
