### ISSUE TITLE
Flow graph issues

### ISSUE THREAD

**Issue by RosaRomeroGomez** [uncharted-aske/HMI#79]
The update of the graph causes different issues (for example, on SIR (functional view), collapse and expand the SIR plate):
- Ellipses are not drawn for input/output nodes. 
- Labels color is updated properly but not the node shapes. 
- Arrow heads disappear after collapsing and expanding again. 

Before the update:
![image](https://user-images.githubusercontent.com/10552785/104655199-59162b00-568b-11eb-8441-6946fee977f3.png)

After the update:
![image](https://user-images.githubusercontent.com/10552785/104655244-71864580-568b-11eb-94b9-270276fe92f2.png)

To test:

**Comment by mj3cheun** [comment]
I didn't notice this when in the current version, a lot has changes since when the issue has been made. Closing
